apiVersion: v1
kind: Service
metadata:
  name: klea-app-service
spec:
  selector:
    app: klea-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
